### ISSUE TITLE
Angular 5 testing broken

### ISSUE THREAD

**Issue by froodley** [trion-development/docker-ng-cli-e2e#5] opened 2018-07-27 13:34 UTC
Hi,

Thanks for the great box.  However, the most recent update broke our tests for our Angular 5 containers.  When I try to revert to the 1.7.4 tag, I get this error:

session not created exception: Chrome version must be >= 66.0.3359.0

Is it still possible to test Angular 5 applications using any version of this box?

Thanks,
froodley

**Comment by everflux** [comment] 2018-07-27 14:10
What is the error with the 6.1.1 tag?

**Comment by froodley** [comment] 2018-07-29 23:23
Running e2e I'm seeing this error:

```
Your global Angular CLI version (6.1.0) is greater than your local
version (1.7.4). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".
Cannot read property 'write' of undefined
TypeError: Cannot read property 'write' of undefined
    at UI.write (/app/node_modules/@angular/cli/ember-cli/lib/ui/index.js:56:23)
    at UI.writeLine (/app/node_modules/@angular/cli/ember-cli/lib/ui/index.js:69:8)
    at Class.run (/app/node_modules/@angular/cli/tasks/serve.js:237:12)
    at check_port_1.checkPort.then.then (/app/node_modules/@angular/cli/commands/e2e.js:116:39)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```


Running unit tests I'm seeing this error:
```
Your global Angular CLI version (6.1.0) is greater than your local
version (1.7.4). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".
27 07 2018 03:27:45.070:INFO [karma]: Front-end scripts not present. Compiling...
27 07 2018 03:28:15.761:INFO [karma]: Karma v2.0.0 server started at http://0.0.0.0:9876/
27 07 2018 03:28:15.762:INFO [launcher]: Launching browser Chrome with unlimited concurrency
27 07 2018 03:28:15.946:INFO [launcher]: Starting browser Chrome
Error: Module build failed: Error: Node Sass does not yet support your current environment: Linux 64-bit with Unsupported runtime (64)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v4.7.2
```

**Comment by everflux** [comment] 2018-07-30 08:08
Do you have a clean node_modules folder and do an npm install inside the container? This error might be caused by mixed dependencies

**Comment by froodley** [comment] 2018-07-31 15:05
I was able to get things going by tying to the 6.0.8 tag.  The culprit is the upgrade in trion/ng-cli from node:8-stretch to node:stretch.  The change from node 8 to node 10 broke a number of my dependencies.

**Comment by everflux** [comment] 2018-07-31 16:08
Could you elaborate which dependencies I affected please? Did removing the modules Folder and clean reinstall  mitigate the problem?

**Comment by everflux** [comment] 2018-08-17 10:31
I can not reproduce the issue due to missing information, closing.

**Closed as completed by everflux** 2018-08-17 10:31 UTC
