### ISSUE TITLE
Update to Chrome 74

### ISSUE THREAD

**Issue by steebchen** [trion-development/docker-ng-cli-e2e#10] opened 2019-05-03 15:22 UTC
```
This version of ChromeDriver only supports Chrome version 74
```

current chrome installed in this docker image is v73.x

**Comment by everflux** [comment] 2019-05-05 12:16
Should be fixed in the :latest tag.
Unfortunately protractor/chrome-webdriver is bumping the required minimum chrome version while beeing kept up-to date, so a build can start to fail without any changes. I don't see how a permanent fix could work due to the implementation of the chrome-webdriver update mechanism. Only option is to build a new image with the latest chrome/chromium version.

**Closed as completed by everflux** 2019-05-05 12:16 UTC

**Comment by steebchen** [comment] 2019-05-05 14:36
Thanks! Maybe you could setup a build once per day somehow and push to latest? GH actions can schedule builds. If not I'll probably fork it and set it up myself in the long term.

**Comment by everflux** [comment] 2019-05-05 14:46
Even once per day will not completely solve the problem, since the release of a newer webdriver/chromebrowser can happen at any time and will break your build in the angular context.
The underlying problem is the automatic behaviour of the webdriver-manager and they themself have this issue in their tracker at regular intervals:
https://github.com/angular/webdriver-manager/issues/376
https://github.com/angular/webdriver-manager/issues/373
https://github.com/angular/webdriver-manager/issues/358
https://github.com/angular/webdriver-manager/issues/353
https://github.com/angular/webdriver-manager/issues/328

To me it looks deeply broken (by design) and there is not to do from the docker image point of view, but of course more regular builds might shadow the real problem. (Currently in the Angular 8 phase, there are not much angular-cli versions coming, which drove more regular builds in the past.)

**Comment by steebchen** [comment] 2019-05-05 14:54
Hm.. I agree. I think I'll just update chrome every time to fix the problem for now (e2es are slow anyway, the extra chrome update won't matter for me).
